### PR TITLE
vscode settings, including fixing automatic env associate per file

### PR DESCRIPTION
**Pull request by elonp**

### CODE REVIEW

**Comment by elonp** [comment]
@ms-lolo - rats-devtools/resources was moved from rats-devtools/src/resources.  I'm not sure if that was on purpose, but it broke the docs commands (probably more).  I moved it back in this PR.  Alternatively, we should fix `self._devtools_component.find_path` - currently (at least in my setup) it returns paths under rats-devtools/src - I am not sure why.

**Comment by ms-lolo** [comment]
hmm sorry about that. looks like i broke a couple things. i think the docs commands are broken but i should have a fix soon

**Review by elonp — COMMENTED** [review]
> hmm sorry about that. looks like i broke a couple things. i think the docs commands are broken but i should have a fix soon 

NP.  Should I complete this PR (and move `rats-devtools/resources` to `rats-devtools/src/resources`) or wait for your fix first?

**Comment by ms-lolo** [comment]
i cherry picked the rename commit you made into my branch and got the pr passing again. let me merge my pr today and then you should be able to pull `main` and continue your settings changes. i can also merge this pr for you later today if you're done making changes. i can pull in and fix any ci issues

**Comment by elonp** [comment]
pre-commit.ci autofix

**Pull request merged**
